cache:
  - '%LOCALAPPDATA%\pip\cache -> requirements.txt'
install:
  - 'C:\Python27\python -m virtualenv venv'
  - '.\venv\Scripts\pip install --upgrade -r requirements.txt nose'
build_script:
  - '.\venv\Scripts\python setup.py bdist_wheel'
test_script:
  - '.\venv\Scripts\nosetests'
artifacts:
  - path: 'dist\*.whl'
#deploy:
#  - provider: GitHub
#    artifact: 'dist\*.whl'
#    draft: false
#    prerelease: false
#    auth_token:
#      secure:
#    on:
#      appveyor_repo_tag: true
